# Generated by Django 5.2.2 on 2025-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий')], default='male', max_length=6),
        ),
    ]
