# Generated by Django 5.2.2 on 2025-06-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
