# Generated by Django 5.2.2 on 2025-06-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_type_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='gender',
        ),
    ]
