# Generated by Django 5.2.2 on 2025-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], default='male', max_length=6),
        ),
    ]
