# Generated by Django 5.2.2 on 2025-06-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
